Labmda job update

diff --git a/.github/workflows/deploy_lambda.yaml b/.github/workflows/deploy_lambda.yaml
--- a/.github/workflows/deploy_lambda.yaml
+++ b/.github/workflows/deploy_lambda.yaml
@@ -30,3 +30,19 @@ jobs:
         aws lambda update-function-code \
           --function-name fastapi-lambda \
           --image-uri ${{ env.AWS_ACCOUNT_ID }}.dkr.ecr.${{ env.AWS_REGION }}.amazonaws.com/fastapi-lambda:latest
+
+    - name: Wait for Lambda update to complete
+      run: |
+        while true; do
+          STATUS=$(aws lambda get-function-configuration --function-name fastapi-lambda --query 'LastUpdateStatus' --output text)
+          if [ "$STATUS" == "Successful" ]; then
+            echo "Lambda update completed successfully."
+            break
+          elif [ "$STATUS" == "Failed" ]; then
+            echo "Lambda update failed."
+            exit 1
+          else
+            echo "Waiting for Lambda update to complete..."
+            sleep 10
+          fi
+        done
